#!/bin/bash

if [ ! -d ${HOME}/.txnotify ]
then
	mkdir ${HOME}/.txnotify
fi

top_entry=$(ls -t ~/.txnotify | head -n 1)

cat ~/.txnotify/${top_entry} | perl -0777 -pe 's/session id:\s(\d+)\nwindow id:\s(\d+)/$1:$2/'
rm -rf ~/.txnotify/${top_entry}
