#!/bin/bash

if [ ! -d ${HOME}/.txnotify ]
then
	mkdir ${HOME}/.txnotify
fi

if [ "$(ls -t ~/.txnotify)" == "" ]
then
	echo "#[fg=colour244]empty"
else
	top_entry=$(ls -t ~/.txnotify | head -n 1)
	fbirth_date=$(stat -c %w ~/.txnotify/${top_entry} | \
		sed 's/\([0-9]\+\)-\([0-9]\+\)-\([0-9]\+\)\W\([0-9]\+\):\([0-9]\+\):\([0-9]\+\).*/\2\/\3 \4:\5:\6/')
	echo "#[fg=colour81]$fbirth_date #[fg=colour252]| #[fg=colour118]$top_entry"
fi
